#Run docker container in the background
#docker-compose up -d
version: '2'
services:
  logstash:
    image: logstash5
    ports:
    - 5140:5140
    depends_on:
    - elasticsearch
    links:
    - elasticsearch:elasticsearch

  kibana:
    image: kibana:5
    ports:
    - 5601:5601
    depends_on:
    - elasticsearch
    links:
    - elasticsearch:elasticsearch

  elasticsearch:
    image: elasticsearch:5
    ports:
    - 9200:9200
    - 9300:9300
